### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by Lolums** [louisameline/php-mail-signature#10]
Hello,

My config file looks like this (with private info left out):

`define('MAIL_RSA_PUBL',
'-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDXkYZ21GegKQQ+k+b3jS6I64aW
+1/Clf6ycveUVo0Y3r5uO7hKJCTpZjwpurw+gctoQ+LKuLNvkFDi6HZTK+GY4aXX
xNZykFdQ6LIzK0b/qdCAXWUOtV8wsImOvbI0ivxJgZ+IDovKyNwWG9RiWpFzTquL
rOnlUl+J4ka1C5k+WwIDAQAB
-----END PUBLIC KEY-----');

// Domain or subdomain of the signing entity (i.e. the domain where the e-mail comes from)
define('MAIL_DOMAIN', 'example.com');

// Allowed user, defaults is "@<MAIL_DKIM_DOMAIN>", meaning anybody in the MAIL_DKIM_DOMAIN domain. Ex: 'admin@mydomain.tld'. You'll never have to use this unless you do not control the "From" value in the e-mails you send.
define('MAIL_IDENTITY', NULL);

// Selector used in your DKIM DNS record, e.g. : selector._domainkey.MAIL_DKIM_DOMAIN
define('MAIL_SELECTOR', 'website');`

The record looks like this: `website._domainkey.example.com. 1800 IN TXT v=DKIM1; k=rsa; t=s; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDXkYZ21GegKQQ+k+b3jS6I64aW+1/Clf6ycveUVo0Y3r5uO7hKJCTpZjwpurw+gctoQ+LKuLNvkFDi6HZTK+GY4aXXxNZykFdQ6LIzK0b/qdCAXWUOtV8wsImOvbI0ivxJgZ+IDovKyNwWG9RiWpFzTquLrOnlUl+J4ka1C5k+WwIDAQAB`

Why is the signature showing up as invalid in my email client (Yandex)?

Thanks!

**Comment by louisameline** [comment]
Hello, I can't tell you. You'll have to double check your configuration and make simple tests with different providers to see if you get better results. Good luck!
