### ISSUE TITLE
Information about line termination

### ISSUE THREAD

**Issue by chrisgraham** [louisameline/php-mail-signature#11]
qmail expects "\n" as the line terminator, when called up using the 'sendmail' executable (which is what PHP's mail command does). They then will internally convert this to "\r\n".

If you use "\r\n" it will convert to "\n\n". This is invisible to mail clients as far as I can see but totally borks DKIM.

I suggest documenting this in your guide, because it's a very big problem causing DKIM to fail.

This is what I have to do:
```
$signed_headers = str_replace("\r\n", "\n", $signature->get_signed_headers($to, $subject, str_replace("\n", "\r\n", $message), str_replace("\n", "\r\n", $headers)));
```

**Comment by louisameline** [comment]
You're right about qmail expecting \n, thank you.

What about just changing this line only:

`mail($to, $subject, $message, $signed_headers.$headers);`

to

```php
mail(
  $to,
  $subject,
  str_replace("\r\n", "\n", $message),
  str_replace("\r\n", "\n", $signed_headers.$headers)
);
```
Could you test it please? Thank you.

**Comment by chrisgraham** [comment]
Hi,

That'd work, and I agree it's better for your docs. We have a pretty complex mailer, I decided the best solution for us was to leave our default path unchanged, and do the fliperoo just for if DKIM is enabled. Better performance for the default case in a system where DKIM use is the exception not the rule.

**Comment by chrisgraham** [comment]
Well actually, you need to be careful about Windows, as PHP uses SMTP there and must use \r\n. On non-Windows (where sendmail executable is used) "\n" is always the safest.

```
if (strtoupper(substr(PHP_OS, 0, 3)) != 'WIN') {
    $message = str_replace("\r\n", "\n", $message);
    $headers = str_replace("\r\n", "\n", $headers);
    $signed_headers = str_replace("\r\n", "\n", $signed_headers);
}
mail($to, $subject, $message, $signed_headers . $headers);
```

**Comment by louisameline** [comment]
I added a note to the readme, thank you. As I'm not sure if all Linux MTAs will tranform `\n` to `\r\n`, I'm not going to advise to always write `\n` altogether. I'd rather warn about just Qmail and others if new names arise.
