### ISSUE TITLE
$to_be_signed possible bug

### ISSUE THREAD

**Issue by OzzyCzech** [louisameline/php-mail-signature#4]
Hi,

there is possible bug on line [430](https://github.com/louisameline/php-mail-signature/blob/master/mail-signature.class.php#L430)

Variable `$to_be_signed` do not exists in function scope.

btw. thanks for saving my time with your perfectly working solution

**Comment by louisameline** [comment]
Hi, thank you for the report and the kind words.

I fixed the warning in v1.0.2. That's the only functional change, the other changes are only the long comment lines getting reformatted.

Thanks again.
