### ISSUE TITLE
How to add DKIM DNS Record

### ISSUE THREAD

**Issue by borsn** [louisameline/php-mail-signature#5]
Hello,

Do I add the Public Key (from beginning to end) as a TXT Record in my DNS?

What is the selector in the config file used for?

Can you please put forth an example on how exactly to configure the DNS part?

Thanks.

**Comment by louisameline** [comment]
Hi, the selector is like a prefix, you can choose whatever you want, as long as you use the same in the DNS record and in your config file.
I would advise you to search for documentation on how to configure your DNS for DKIM in your favorite search engine, you'll find plenty of information on the subject, certainly better than what I could come up with in the limited time that I have. Thank you.
