### ISSUE TITLE
Attachment

### ISSUE THREAD

**Issue by willparis** [louisameline/php-mail-signature#9]
I'm using php-mail-signature and i am very grateful as DKIM was quite tricky to set up when i tried to do it from scratch.
It works fine for me, but when i add an attached file to the mail, the body hash is not the one expected. Did you try it already?
Thanks again for your work!

**Comment by louisameline** [comment]
Thank you for your message! No, I haven't tried that yet, I need to find a moment to test it!

**Comment by willparis** [comment]
Despites my many tests, it turns out i had a slightly difference between my code with and without attachment. I put "\n" where i should have put "\n\n", which messes with the body hash (at least with my provider). Your script works fine with attached files, thank you again for your work !

**Comment by louisameline** [comment]
Ok, thank you for the follow-up, this had slipped off of my mind. Good to know that everything is working fine :)
